<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <PackageReference Include="PdfPig" Version="0.1.9" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CashPilot.Domain\CashPilot.Domain.csproj" />
  </ItemGroup>
</Project>
